[package]
name = "aes-ccm"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>", "DurandA <arnaud.durand@unifr.ch>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
aes = "0.3.2"

[dev-dependencies]
hex-literal = "0.2.0"
